### ISSUE TITLE
Alexa::ResponseError, even though I signed up and generated secret_keys 

### ISSUE THREAD

**Issue by tonyvince** [morgoth/alexa#9] opened 2017-02-05 06:05 UTC
I am getting `Alexa::ResponseError (AWS was not able to validate the provided access credentials):`
This is my code

```
@client = Alexa::Client.new(access_key_id: ENV['AWIS_KEY_ID'], secret_access_key: ENV['AWIS_ACESS_KEY'])
url_info = @client.url_info(url: params[:alexa_rank][:given_url])
```

what might be the issue ??

**Comment by grammakov** [comment] 2017-11-16 09:02
Hi Tony, I'm experiencing similar issue. Were you able to solve it yet? What kind of keys you used?

**Comment by tonyvince** [comment] 2017-11-16 09:06
@grammakov my problem was I didn't provide my credit card details for AWS account. Please make sure you submit ur card details and verify your AWS account first

**Comment by grammakov** [comment] 2017-11-16 09:08
@tonyvince definitely not my case. I think the problem is that I am not allowed to use AWIS as I don't see it in my available product list. Thanks for replying though!

**Comment by morgoth** [comment] 2017-12-28 10:11
So looks like problem with the account setup. Closing then, thanks for sharing your findings.

**Closed by morgoth** 2017-12-28 10:11 UTC
